services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_user=root
      - MYSQL_DATABASE=tests
    ports:
      - "3306:3306"
