name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: $PNPM_VERSION
      - uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: pnpm
      - run: pnpm i --frozen-lockfile

  Lint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: $PNPM_VERSION
      - uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: pnpm
      - run: pnpm lint

  Unit-test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: $PNPM_VERSION
      - uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: pnpm
      - run: pnpm test:unit
